# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: New variable group 10-Jul

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    addToPath: true
    architecture: 'x64'

- script: |
    pip install requests setuptools wheel 
    pip install databricks-api databricks-cli
  displayName: 'Load Python Dependencies'

- script: |
    echo "y
    $(WORKSPACE-REGION-URL)
    $(db)" | databricks configure --token
  displayName: 'Configure DB Cli'

- script: |
    databricks secrets create-scope --scope $(SECERET-SCOPE-NAME)
  displayName: 'Creating a secret scope'

- script: databricks secrets list-scopes
  displayName: "List secrets"

- script: databricks secrets put --scope $(SECERET-SCOPE-NAME) --key $(SCOPE-KEY-NAME) --string-value $(key)
  displayName: 'Create scope with key'

- script: |
    python $(System.DefaultWorkingDirectory)/main.py $(CSE-DEVELOP-PAT) $(WORKSPACE-REGION-URL) $(NOTEBOOK_NAME)
  displayName: 'Deploy Notebook'



